#pragma config(Sensor, in1,    lineFollower,   sensorLineFollower)
#pragma config(Sensor, in2,    lightSensor,    sensorReflection)
#pragma config(Sensor, dgtl1,  bumper,         sensorTouch)
#pragma config(Sensor, dgtl2,  conductor,      sensorDigitalIn)
#pragma config(Motor,  port1,           shaker,        tmotorVex269, openLoop)
#pragma config(Motor,  port2,           chuteGate,     tmotorServoStandard, openLoop)
#pragma config(Motor,  port3,           testGate,      tmotorServoStandard, openLoop)
#pragma config(Motor,  port4,           rotator,       tmotorServoStandard, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/* Projet: 3.3.1 Material Sorter
 * Names: Thomas Nguyen and Kristin Ottofy
 * Course: POE Winter Training
 * Date: 1/16/2014
*/

void StartShaker();								// help the marbles fall out of the funnel
void OpenChuteGate();							// let one ball slide into the testing area
void OpenTestGate();							// open the gate to let the marble slide into the cup
int TestConductivity();						// test for conductivity
int TestMaterial();								// test for material
int LineFollowerTest();						// take average of 4 line follower tests
int DetermineMaterial(int value);	// determine the materal based on raw sensor value
void MoveRotator(int material);		// move servo with ramp to let ball slide to appropriate cup

/* This is a program to operate the material sorter.
 * General idea is to open the chute gate to let a ball silde into the testing area,
 * test the marble, rotate the servo to */
task main()
{
	untilTouch(bumper);		// wait until bumper is hit to start
	OpenTestGate();				// release any balls in the testing area
	StartShaker();				// shake the funnel

	while (1)							// always
	{
		OpenChuteGate();		// open chute gate to let ball slide into testing area
		int material = TestMaterial();	// test the material
		wait(.5);
		MoveRotator(material);					// position servo ramp at the correct cup
		wait(.5);
		OpenTestGate();			// open second gate to let ball fall into cup
	}
}

/* void OpenChuteGate() opens the first gate to let one ball slide into the testing
* area. */
void OpenChuteGate()
{
	setServo(chuteGate, 14);		// open gate
	wait(.1);
	setServo(chuteGate, 0);			// close gate
}

/* void OpenTestGate() lets the tested ball roll out into the cup. */
void OpenTestGate()
{
	setServo(testGate, -30);		// open gate
	wait(.4);
	setServo(testGate, 0);			// close gate
	wait(.1);
}

/*  int TestMaterial() first checks conductivity. If conductivity test fails,
 * it calls to test the marble on the line follower.
 * Returns 0 for plastic, 1 for wood, 2 for metal. */
int TestMaterial()
{
	int material = TestConductivity(); 		// if material is conductive, material is 1

	if (material == -1)										// material is not conductive
		material = LineFollowerTest();			// test one line follower

	return material;
}

/* void TestConductivity() tests the conductivity of a marble. It has a timer of 1 sec.
 * If any conductivity is sensed in that 1 second, this function will end.
 * Returns 2 for metal. Returns -1 for failed conductivity test. */
int TestConductivity()
{
	ClearTimer(T1);
	while (time100[T1] < 10) 								// wait for ball to roll past wires for 1 sec
		if (SensorValue[conductor] == 0)			// material is metal, return 2
			return 2;
	return -1;															// material is not metal, return 1
}

/* Take 4 tests with the marble on the line follower. Calculate the average.
 * Call function to determine material number and return that back to the
 * parent function. */
int LineFollowerTest()
{
	wait(.5);
	int test1 = SensorValue[lineFollower];
	wait(.1);
	int test2 = SensorValue[lineFollower];
	wait(.1);
	int test3 = SensorValue[lineFollower];
	wait(.1);
	int test4 = SensorValue[lineFollower];
	int average = (test1 + test2 + test3 + test4) / 4;		// taking average of tests

	return DetermineMaterial(average);
}

/* int DetermineMaterial(int value) takes in a raw value read from the lineFollower.
 * This function is really only necessary for wood and plastic, but it makes for a nice
 * check on metal.
 * Returns a 0 for plastic, 1 for wood, or 2 for metal. */
int DetermineMaterial(int value)
{
	if (value <= 800)												// material is plastic
		return 0;
	else if (value > 800 && value <= 2200)	// material is wood
		return 1;
	else 																 		// material is metal
		return 2;
}

/* MoveRotator(int material) takes in 0, 1, or 2, and tells the servo
* to rotate to the location of the cup designated. */
void MoveRotator(int material)
{
	if (material == 0)											// material is plastic
	{
		setServo(rotator, -75);
	}
	else if (material == 1)							 		// material is wood
	{
		setServo(rotator, 0);
	}
	else																		// material is metal
	{
		setServo(rotator, 75);
	}
}

/* StartShaker rotates the motor that will help the marbles fall out of the funnel*/
void StartShaker ()
{
	startMotor(shaker, 127);
}
